# Generated by Django 4.2.3 on 2023-07-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organ',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='panel',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='test',
            name='info_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='test',
            name='normal_reference',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='test',
            name='unit_of_measure',
            field=models.TextField(),
        ),
    ]
