# Generated by Django 4.2.3 on 2023-07-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_panel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
